"""
Django settings for learning_log project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gzf^^zvt=*v6x5(xva8f4_^vlencuii)ewv8q)890afmd65yqy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #第三方应用程序
    'bootstrap3',

    #我的应用程序
    'learning_logs',
	'users',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'learning_log.urls'

##TEMPLATES = [
##    {
##        'BACKEND': 'django.template.backends.django.DjangoTemplates',
##        'DIRS': [],
##        'APP_DIRS': True,
##        'OPTIONS': {
##            'context_processors': [
##                'django.template.context_processors.debug',
##                'django.template.context_processors.request',
##                'django.contrib.auth.context_processors.auth',
##                'django.contrib.messages.context_processors.messages',
##            ],
##        },
##    },
##]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # insert your TEMPLATE_DIRS here
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'learning_log.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# 加入下面的配置
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

#为了安全起见，在生产环境下需要关闭 DEBUG 选项以及设置允许访问的域名
DEBUG = False
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.dyjlearning.cn']
#我的设置
LOGIN_URL = '/users/login/'




#django-bootstrap3的设置
BOOTSTRAP3 = {
      'include_jquery':True,
      }

# #Heroku设置
# if os.getwd() == '/app':
	# import dj_database_url
	# DATABASES = {
		# 'default':dj_database_url.config(default='postgres://localhost')
	# }
	
	# #让request.is_secure()承认X=Forwarded-Proto头
	# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
	
	# #支持所有的主机头（host header）
	# ALLOWED_HOSTS = ['*']
	
	# #静态资产配置
	# BASE_DIR = os.path.dirname(os.path.abspath(__file__))
	# STATIC_ROOT = 'staticfiles'
	# STATICFILES_DIRS = (
		# os.path.join(BASE_DIR, 'static'),
	# )